server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://100.65.207.47:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://100.70.130.65:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://100.66.172.163:1003
    cart:
      path: /cart/**
      url: http://100.65.28.248:1004/api/v1
